import type { ModelProfile } from "./types.js";

/**
 * Registry of all supported fal.ai models with their profiles.
 * This is the source of truth for model selection decisions.
 */
export const MODEL_REGISTRY: ModelProfile[] = [
  // ─── Image Models ───────────────────────────────────────────────
  {
    id: "fal-ai/flux/schnell",
    name: "FLUX.1 Schnell",
    type: "image",
    costDescription: "$0.003 per megapixel",
    costPerUnit: 0.003,
    unit: "megapixel",
    maxResolution: "2048x2048 (4MP)",
    strengths: [
      "Extremely fast (1-4 steps)",
      "Very cheap",
      "Good for quick iteration and drafts",
    ],
    weaknesses: [
      "Lower detail than dev/pro",
      "Mediocre text rendering",
      "Less prompt adherence",
    ],
    supportsReferenceImage: false,
    supportsTextRendering: false,
    speedTier: "fast",
    qualityTier: "draft",
  },
  {
    id: "fal-ai/flux/dev",
    name: "FLUX.1 Dev",
    type: "image",
    costDescription: "$0.012 per megapixel",
    costPerUnit: 0.012,
    unit: "megapixel",
    maxResolution: "2048x2048 (4MP)",
    strengths: [
      "Good balance of quality and cost",
      "Strong prompt adherence",
      "12B parameters",
    ],
    weaknesses: [
      "Mediocre text rendering",
      "Slower than schnell",
    ],
    supportsReferenceImage: false,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "standard",
  },
  {
    id: "fal-ai/flux-2-pro",
    name: "FLUX.2 Pro",
    type: "image",
    costDescription: "$0.03 per megapixel",
    costPerUnit: 0.03,
    unit: "megapixel",
    maxResolution: "2048x2048 (4MP)",
    strengths: [
      "Highest quality FLUX model",
      "Excellent photorealism",
      "Best prompt adherence",
      "Zero-config — great defaults",
    ],
    weaknesses: [
      "Most expensive FLUX tier",
      "Still not great at text in images",
    ],
    supportsReferenceImage: false,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "high",
  },
  {
    id: "fal-ai/flux-general",
    name: "FLUX General (ControlNet + IP-Adapter)",
    type: "image",
    costDescription: "$0.012 per megapixel",
    costPerUnit: 0.012,
    unit: "megapixel",
    maxResolution: "2048x2048 (4MP)",
    strengths: [
      "Accepts reference images via IP-Adapter",
      "ControlNet support (canny, depth, pose)",
      "LoRA stacking",
      "Best for style-matching with references",
    ],
    weaknesses: [
      "More complex to configure",
      "Requires reference image for best results",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "standard",
  },
  {
    id: "fal-ai/flux-lora",
    name: "FLUX LoRA",
    type: "image",
    costDescription: "$0.012 per megapixel",
    costPerUnit: 0.012,
    unit: "megapixel",
    maxResolution: "2048x2048 (4MP)",
    strengths: [
      "Custom style via LoRA weights",
      "Image-to-image support",
      "Multiple LoRAs can be stacked",
    ],
    weaknesses: [
      "Requires pre-trained LoRA weights",
      "Setup overhead",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "standard",
  },
  {
    id: "fal-ai/ideogram/v3",
    name: "Ideogram V3",
    type: "image",
    costDescription: "$0.03–$0.09 per image (3 tiers)",
    costPerUnit: 0.03,
    unit: "image",
    maxResolution: "1024x1024+",
    strengths: [
      "Best-in-class text rendering",
      "Excellent for typography, posters, marketing",
      "3 quality tiers (turbo/balanced/quality)",
      "Precise text placement",
    ],
    weaknesses: [
      "Higher cost at quality tier",
      "Less versatile for pure photorealism",
    ],
    supportsReferenceImage: false,
    supportsTextRendering: true,
    speedTier: "standard",
    qualityTier: "high",
  },
  {
    id: "fal-ai/recraft/v3/text-to-image",
    name: "Recraft V3",
    type: "image",
    costDescription: "$0.04 raster / $0.08 vector per image",
    costPerUnit: 0.04,
    unit: "image",
    maxResolution: "1024x1024+",
    strengths: [
      "SOTA image quality (ELO 1172)",
      "Vector art output",
      "Strong graphic design capability",
      "Brand style consistency",
    ],
    weaknesses: [
      "Higher cost",
      "Less flexible for photorealism",
    ],
    supportsReferenceImage: false,
    supportsTextRendering: true,
    speedTier: "standard",
    qualityTier: "high",
  },

  // ─── Video Models ───────────────────────────────────────────────
  {
    id: "fal-ai/ltx-2/image-to-video/fast",
    name: "LTX 2.0 Fast",
    type: "video",
    costDescription: "~$0.04 per second (1080p)",
    costPerUnit: 0.04,
    unit: "second",
    maxResolution: "1080p",
    strengths: [
      "30x faster than diffusion-based",
      "Very affordable",
      "Good for quick video drafts",
    ],
    weaknesses: [
      "Lower motion quality than premium",
      "Less cinematic",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "fast",
    qualityTier: "draft",
  },
  {
    id: "fal-ai/ltx-2/image-to-video",
    name: "LTX 2.0",
    type: "video",
    costDescription: "$0.04 per second (1080p)",
    costPerUnit: 0.04,
    unit: "second",
    maxResolution: "1080p",
    strengths: [
      "Good quality at low cost",
      "Up to 20 seconds",
      "25-50 fps",
    ],
    weaknesses: [
      "Not as cinematic as Veo/Kling",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "standard",
  },
  {
    id: "fal-ai/wan/v2.6/image-to-video/api",
    name: "WAN 2.6",
    type: "video",
    costDescription: "~$0.06 per second",
    costPerUnit: 0.06,
    unit: "second",
    maxResolution: "4K",
    strengths: [
      "Natural-looking motion",
      "Up to 4K resolution",
      "Good mid-range option",
    ],
    weaknesses: [
      "Slower than LTX",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "standard",
  },
  {
    id: "fal-ai/veo3.1/fast/image-to-video",
    name: "Veo 3.1 Fast",
    type: "video",
    costDescription: "$0.10/sec (no audio) / $0.15/sec (audio)",
    costPerUnit: 0.1,
    unit: "second",
    maxResolution: "1080p",
    strengths: [
      "High quality at half the cost of full Veo",
      "Optional audio generation",
      "Cinematic output",
    ],
    weaknesses: [
      "Pricier than LTX/WAN",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "high",
  },
  {
    id: "fal-ai/veo3.1/image-to-video",
    name: "Veo 3.1",
    type: "video",
    costDescription: "$0.20/sec (no audio) / $0.40/sec (audio)",
    costPerUnit: 0.2,
    unit: "second",
    maxResolution: "4K",
    strengths: [
      "State-of-the-art video quality",
      "Native audio generation",
      "Up to 4K resolution",
      "Best cinematic quality",
    ],
    weaknesses: [
      "Most expensive video model",
      "Slower generation",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "slow",
    qualityTier: "high",
  },
  {
    id: "fal-ai/kling-video/v3/pro/image-to-video",
    name: "Kling 3.0 Pro",
    type: "video",
    costDescription: "~$0.10 per second",
    costPerUnit: 0.1,
    unit: "second",
    maxResolution: "1080p",
    strengths: [
      "Excellent motion fluidity",
      "Advanced character motion",
      "Audio support",
    ],
    weaknesses: [
      "Premium pricing",
    ],
    supportsReferenceImage: true,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "high",
  },
  {
    id: "fal-ai/cogvideox-5b",
    name: "CogVideoX-5B",
    type: "video",
    costDescription: "$0.20 per video (flat)",
    costPerUnit: 0.2,
    unit: "video",
    maxResolution: "720p",
    strengths: [
      "Flat pricing — predictable cost",
      "Open-source weights",
      "Good for text-to-video (no reference image needed)",
    ],
    weaknesses: [
      "Lower resolution (720p)",
      "Shorter clips",
      "Less cinematic",
    ],
    supportsReferenceImage: false,
    supportsTextRendering: false,
    speedTier: "standard",
    qualityTier: "draft",
  },
];

export function getModelById(id: string): ModelProfile | undefined {
  return MODEL_REGISTRY.find((m) => m.id === id);
}

export function getImageModels(): ModelProfile[] {
  return MODEL_REGISTRY.filter((m) => m.type === "image");
}

export function getVideoModels(): ModelProfile[] {
  return MODEL_REGISTRY.filter((m) => m.type === "video");
}
